'use client';

/**
 * MermaidRenderer Component
 *
 * Renders Mermaid diagrams with theme support and error handling.
 *
 * Based on: specs/005-markdown-reader/spec.md User Story 3
 * Reference: specs/005-markdown-reader/research.md Section 3
 *
 * Security Note: This component uses innerHTML to insert SVG generated by Mermaid.
 * This is safe because:
 * 1. Mermaid's securityLevel: 'strict' prevents JavaScript execution
 * 2. Input is Mermaid DSL syntax, not arbitrary HTML
 * 3. Mermaid's render() sanitizes output SVG
 */

import { useEffect, useRef, useState, useId, useCallback, memo } from 'react';
import mermaid from 'mermaid';
import { getMermaidThemeConfig } from '@/lib/reader/mermaid-themes';
import { cn } from '@/lib/utils';

export interface MermaidRendererProps {
  /** Mermaid diagram code to render */
  code: string;
  /** Theme for the diagram (dark, light, or reading) */
  theme?: 'dark' | 'light' | 'reading';
  /** Custom ID for the diagram element */
  id?: string;
  /** Custom aria-label for accessibility */
  ariaLabel?: string;
  /** Additional CSS classes */
  className?: string;
}

/**
 * Client component that renders Mermaid diagrams with theme support
 * and comprehensive error handling.
 */
function MermaidRenderer({
  code,
  theme = 'dark',
  id,
  ariaLabel = 'Mermaid diagram',
  className,
}: MermaidRendererProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const uniqueId = useId();
  const diagramId = id || `mermaid-${uniqueId.replace(/:/g, '')}`;

  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Track previous values to prevent unnecessary re-renders
  const prevCodeRef = useRef<string | null>(null);
  const prevThemeRef = useRef<string | null>(null);

  const renderDiagram = useCallback(async () => {
    if (!containerRef.current) return;

    // Skip if code is the same and theme hasn't changed
    if (prevCodeRef.current === code && prevThemeRef.current === theme) {
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      // Get theme configuration
      const themeConfig = getMermaidThemeConfig(theme);

      // Initialize mermaid with theme settings
      // securityLevel: 'strict' prevents XSS by blocking JavaScript in diagrams
      mermaid.initialize({
        ...themeConfig,
        startOnLoad: false,
        securityLevel: 'strict',
      });

      // Handle empty code
      if (!code || code.trim() === '') {
        if (containerRef.current) {
          containerRef.current.textContent = '';
        }
        setIsLoading(false);
        return;
      }

      // Generate unique ID for this render
      const renderId = `${diagramId}-render-${Date.now()}`;

      // Render the diagram - Mermaid sanitizes output with strict security
      const { svg } = await mermaid.render(renderId, code);

      // Insert sanitized SVG into container
      // Safe: Mermaid's strict mode produces sanitized SVG without executable scripts
      if (containerRef.current) {
        containerRef.current.innerHTML = svg;
      }

      // Update previous values
      prevCodeRef.current = code;
      prevThemeRef.current = theme;
      setError(null);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to render diagram';
      setError(errorMessage);
      prevCodeRef.current = null; // Reset to allow retry
      prevThemeRef.current = null;
    } finally {
      setIsLoading(false);
    }
  }, [code, theme, diagramId]);

  // Render on mount and when code/theme changes
  useEffect(() => {
    renderDiagram();
  }, [renderDiagram]);

  const hasError = error !== null;

  return (
    <div
      data-testid="mermaid-renderer"
      data-diagram-id={diagramId}
      data-theme={theme}
      data-loading={isLoading ? 'true' : undefined}
      data-error={hasError ? 'true' : undefined}
      role="img"
      aria-label={ariaLabel}
      aria-busy={isLoading}
      className={cn(
        'mermaid-container',
        hasError && 'mermaid-error',
        className
      )}
    >
      {/* Error state */}
      {hasError && (
        <div className="mermaid-error-content">
          <div role="alert" className="text-red-500 mb-2">
            Error rendering diagram: {error}
          </div>
          <pre className="text-sm text-muted-foreground bg-muted p-2 rounded overflow-auto">
            {code}
          </pre>
        </div>
      )}

      {/* Loading state (visual indicator) */}
      {isLoading && !hasError && (
        <div className="mermaid-loading flex items-center justify-center p-4 text-muted-foreground">
          Loading diagram...
        </div>
      )}

      {/* SVG container - hidden during loading/error */}
      <div
        ref={containerRef}
        className={cn(
          'mermaid-svg-container',
          (isLoading || hasError) && 'hidden'
        )}
      />
    </div>
  );
}

export default memo(MermaidRenderer);
